### ISSUE TITLE
draw.io - Error: Invalid file data

### ISSUE THREAD

**Issue by AK-CCM** [WhiskeyTang0F0xtr0t/unifi#3]
Hello,

if I try to open the .xml-files in draw.io desktop app as library the error message "Invalid file data" occours.
I'm using the version 2.4.7.17. Also I tried it with the Online App at https://app.diagrams.net/ – what did I wrong?

Best regards,
Andreas

**Comment by WhiskeyTang0F0xtr0t** [comment]
Open/create a drawing and drag the file over to the window.
